### ISSUE TITLE
Problema com geração de boleto no BB

### ISSUE THREAD

**Issue by esoubihe** [claudiosmweb/woocommerce-boleto#18]
Boleto fica em branco. Segue análise do BB a respeito da geração de um boleto através do plugin:

Campo Espécie Doc.: preencher com o tipo de documento que gerou a cobrança. Ex: RC (recibo); DM (duplicata mercantil); DS (duplicata de serviço); OU (outros); NF (nota fiscal); etc 

Campo Aceite: informar A para Aceite ou N para Não Aceite. Se for informado A (aceite); isso implica que no caso de ser encaminhado ao protesto a duplicata assinada pelo sacado, obrigatoriamente, deverá ser anexada ao título. 
Com a opção N (sem aceite), o título poderá ser encaminhado ao cartório sem a duplicata, sendo que, quando solicitado pelo cartório, poderá ser enviada uma cópia autenticada da nota fiscal (a opção N é mais freqüentemente utilizada). 

Campo Sacado: informar o nome, cpf ou cnpj e o endereço completo do sacado (inclusive bairro). 

Campo Nosso Número: o nosso número é composto de 17 posições sem DV, sendo obrigatoriamente as 7 primeiras posições o número do convênio e as 10 posições restantes um sequencial livre a partir de 0000000001 não podendo haver duplicidade. 
Ex: 25306860000000001. 

Campo Instruções: Foi informado neste campo dados para cobrança de multa após vencimento. Por ser uma carteira sem registro, o cliente poderá solicitar à agência de relacionamento a alteração, no cadastro da carteira no Banco, dos parâmetros multa/juros, hoje cadastrados com 0 %. Desse modo, todo título dessa carteira que for registrado no Banco, terá automaticamente registrado a instrução de multa/juros com os percentuais cadastrados, para que seja cobrado tais valores em qualquer meio eletrônico (internet ou terminais de auto atendimento) e não apenas no guichê de caixa. 

Linha digitável e código de barras -  (   ) Aprovado      ( x ) Reprovado 

Código de Barras: montar o código de barras de acordo com o anexo 4 do manual em anexo. 

Código de Barras: montar o código de barras com as seguintes dimensões: Comprimento total igual a 103mm e altura total igual a 13mm. 

Linha Digitável: montar a linha digitável de acordo com os anexos 4,6,7,8 e 10 do manual em anexo. 

Especificações FEBRABAN - (  ) Aprovado    ( x ) Reprovado   

Campo Processamento de Dados: o nome correto do campo é Data de Processamento. Corrigir 

Resultado: boletos  NÃO APROVADOS.

**Comment by guicma** [comment]
Fala Claudio,

Maninho, me diz uma coisa, eu estou usando um plugin chamado Advanced Order Export For WooCommerce.
Nele eu não consigo obter a informação mais importante que é o CPF ou CNPJ que já foram configurados com o plugin WooCommerce Extra Checkout Fields for Brazil.
Ou seja, essa informação não aparece ao exportar os pedidos, nem mesmo no meu banco de dados.
Como faço para incluir esse dado?

**Comment by claudiosanches** [comment]
@guicma sua questão não me parece relacionada com esse plugin aqui ou com esta thread.
