### ISSUE TITLE
WooCommerce Boleto, Homologação CAIXA

### ISSUE THREAD

**Issue by livingsthon** [claudiosmweb/woocommerce-boleto#47]
Olá, tudo bem?

Estou com um problema para homologar meus boletos com a CAIXA, eles me pedem 10 boletos com o campo em parentese variando de 0-9, "10492.40003 00546.081506 00000.3428(2)4 2 63640000037000", o problema é que já gerei vários boletos e esse campo não varia, gostaria de saber como posso resolver isso, provavelmente fiz alguma coisa errada na tela de configuração kk,

Desde já, grato.

**Comment by claudiosmweb** [comment]
Não faço a mínima ideia, principalmente que é o código do BoletoPHP que gera os boletos e integramos aqui seguindo a documentação deles.
Além que já vi outras pessoas utilizando boletos da Caixa sem este processo.

**Comment by livingsthon** [comment]
Tudo bem, estava dando uma lida aqui e acho que me mandaram a homologação do boleto errado, obrigado pela ajuda.
