### ISSUE TITLE
Mostrar o valor do boleto com desconto

### ISSUE THREAD

**Issue by mruoppolo** [claudiosmweb/woocommerce-boleto#48]
Olá, tudo bem?

Estou utilizando o plugin Woocommerce Boleto e preciso conseguir colocar na página do produto um sisteminha dando ênfase ao pagamento com boleto, mostrando o valor que o produto ficaria já com o desconto no boleto, igualzinho o do kabum:
![screenshot_1](https://cloud.githubusercontent.com/assets/11514526/6681594/f073376a-cc47-11e4-80ac-a23ccce8ea85.png)

 http://www.kabum.com.br/produto/62574/smartphone-microsoft-lumia-435-processador-dual-c-

Eu preciso pegar o valor do desconto do boleto diretamente do plugin.

Como eu posso fazer??

Muito obrigado pela ajuda

**Comment by claudiosmweb** [comment]
Este plugin não da descontos para boleto e de qualquer frma isso que você quer fazer é fora do escopo deste plugin.
