### ISSUE TITLE
Digito no campo Nosso Numero é possivel?

### ISSUE THREAD

**Issue by rodrigobrando** [claudiosmweb/woocommerce-boleto#50]
Bom dia!
A dias venho tendo problema com o banco ao qual trabalhamos eles vem pedindo algumas mudanças no boleto, algumas eu consegui outras não, mas a mais importante de todas é que seja separado o ultimo digito do campo Nosso Numero por um ifem. 
Existe esta possibilidade?

**Comment by claudiosmweb** [comment]
Os boletos são gerados com o código do BoletoPHP, não fiz nenhuma alteração no código deles.
Mas sinta-se livre para você fazer as alterações que precisar.

**Comment by rodrigobrando** [comment]
Ok Claudio muito obrigado pela resposta! Vou torturar um pouco o funcionario da Caixa antes de alterar o codigo do plugin.

Grato
