### ISSUE TITLE
Boletos não abrem

### ISSUE THREAD

**Issue by mehvsc** [claudiosmweb/woocommerce-boleto#51]
Boletos nao abrem em uma instalação do wordpress em servidor windows.
em minha hospedagem windows os links permanentes me obrigam a usar o /index.php/alguma coisa
quando o plugin gera o boleto ele nao esta pegando essa "base", entao nao esta funcionando os links que sao gerados, se eu for manualmente no link e alterar o boleto aparece, 
acredito ser somente um ajuste na chamada dos links do boleto. 

obrigado,
Marcelo Hoepfner

**Comment by claudiosmweb** [comment]
Mude para linux ou use o filtro `woocommerce_boleto_url` para corrigir o link no windows.
