### ISSUE TITLE
Habilitar boleto para escolha da moeda BRL

### ISSUE THREAD

**Issue by Adansix** [claudiosmweb/woocommerce-boleto#54]
Olá! 
Os produtos do meu site vão ser vendidos em Euro, mas possuo um conversor de moedas e também PayPal que parecem funcionar até onde testei.
Como a intenção é vender pro Brasil e facilitar essa venda, existe alguma forma de habilitar o boleto caso a escolha da moeda seja Real?

Valeu pelo plugin! =D

**Comment by Adansix** [comment]
Nevermind. Era só habilitar a opção "Is multiple allowed" do Plugin WooCommerce Currency Switcher. Valeu mesmo pelo Boleto! Aparentemente tá funcionando agora! =D

**Comment by claudiosmweb** [comment]
@Adansix sim, por padrão o plugin só vai mostrar a opção de boleto se na hora do checkout o pedido for em BRL :)
