### ISSUE TITLE
Integração Banco Itau

### ISSUE THREAD

**Issue by cbarufe** [claudiosmweb/woocommerce-boleto#56]
Olá Cláudio, obrigado pelas suas contribuições.
O plugin está todo configurado com os dados fornecidos pelo banco mas quando finalizo a compra e clico para gerar o boleto sou redirecionado para uma página inválida. O que posso estar fazendo de errado? 
Outra dúvida (não sei se posso pedir por aqui) é sobre o Ad-On PDF que simplesmente não faz nenhuma alteração. Após instalado não é criado nenhuma seção para configurar o PDF.
Obrigado.

**Comment by claudiosmweb** [comment]
Para itau é melhor usar: https://wordpress.org/plugins/wc-itau-shopline/
