### ISSUE TITLE
Sugestão para próxima versão

### ISSUE THREAD

**Issue by TheruSantana** [claudiosmweb/woocommerce-boleto#58]
Cláudio, aqui no github está dando pau pra dar sugestões no pull requests, então vai por aqui mesmo....

Você ficou sabendo que não há mais carteira sem registro? Acho que o projeto Boletophp não vai implementar novos arquivos na estrutura dele para gerar os arquivos cnab que podem ser enviados aos bancos pela dificuldade em testar para cada banco, etc e como este seu projeto do boleto utiliza o Boletophp creio que também não irá pois foge do escopo da sua proposta. É uma pena pois de todos os seus plugins esse é oque eu considero o mais top dos que já vi para e-commerce inclusive de outras plataformas. Funciona lindamente, parece até nativo do Woocommerce, rs

Dai minha sugestão é de que você de um stop nesta versão 1.5.3 e inicie uma outra utilizando além do Boletophp o cnabPHP, já conhece ele? O projeto é do Anderson Danilo e já ta gerando e lendo corretamente os arquivos de remessa nos formatos CNAB 240 e 400 para a maior parte dos bancos.

Veja essa possibilidade, e sucesso ai!

**Comment by claudiosmweb** [comment]
Não vou fazer isso.
