### ISSUE TITLE
Bradesco - Adicionar carteira 26

### ISSUE THREAD

**Issue by ViLourenco** [claudiosmweb/woocommerce-boleto#59]
Fala Cláudio, tudo certo?
Precisei inserir a carteira 26 na lista, do banco Bradesco! Acho que talvez mais pessoas precisarão disso!
Abraços.

**Comment by claudiosmweb** [comment]
E funciona?
Gerente do banco homologou?

**Comment by ViLourenco** [comment]
Sim, o comunicado para que setássemos esta carteira partiu do próprio banco, realizamos um pagamento e foi certinho. Apenas para ter certeza fizemos mais 3, mas o primeiro já deu ok.

**Comment by claudiosmweb** [comment]
Beleza, vou adicionar na próxima versão do plugin então.
Obrigado.

**Comment by ViLourenco** [comment]
Ok! Mas eu já te mandei um pull-request tb

Enviado do meu iPhone

**Comment by hostbraga** [comment]
ola bom dia , estou usando o modulo porem , ao pagar o boleto a maquina nao le , tipo que nao existe boleto bradesco as configuraçoes estao certinhas o que devo fazer?

**Comment by claudiosmweb** [comment]
Fechado por #60

**Comment by raifone** [comment]
Boa tarde Claudio tudo bem contigo? 
Meu amigo estou com um problema na geração do boleto bancário carteira 26 do Bradesco. Baixei a sua atualização, configurei tudo dentro dos padrões. 

Ele gera o boleto bancário para pagamento, porém na hora de pagar informa que o penúltimo campo digitado é inválido. Sabe me dizer o que pode estar acontecendo? 

Desde já muito obrigado, um abraço!

![pgto](https://user-images.githubusercontent.com/5004275/28733053-bef5837e-73b0-11e7-94e0-1fc69ee1ec8f.jpeg)

**Comment by raifone** [comment]
@claudiosanches , meu amigo teria alguma solução em relação a minha pergunta? Abraços.
