### ISSUE TITLE
Sugestão: Verificação de Boleto pago

### ISSUE THREAD

**Issue by willph** [claudiosmweb/woocommerce-boleto#61]
Não sei se tem, mas gostaria de sugerir pra próxima versão se for possível a verificação que o boleto foi pago ou ainda continua pendente. Tanto pro adm quanto para o cliente.
Sou novo aqui, e peço desculpa se estiver postando em local errado.

Obrigado pela criação e disponibilização dele gratuitamente.

**Comment by claudiosmweb** [comment]
Não vamos fazer isso.
Se quiser fazer, sinta-se livre.
