### ISSUE TITLE
Erro ao gerar boleto BB

### ISSUE THREAD

**Issue by pterenzi** [claudiosmweb/woocommerce-boleto#63]
Oi Cláudio,

Configurei o Woocommerce Boleto para recebimento via BB - acredito que corretamente - mas recebo o erro de linha digitável inválida. O boleto gerado é 00190.00009 02905.394009 00044.855104 4 68520000000500.
Você pode me dar uma luz?
Grato.

**Comment by pterenzi** [comment]
Cláudio?

**Comment by claudiosmweb** [comment]
Tem que ver com o gerente do banco, ver se os dados estão corretos.
Mas não acho que tem algo que podemos alterar no código, ainda mais que daqui uns 6 meses vai ser proibido/impossível trabalhar com boletos sem registro.

**Comment by h3nr1ke** [comment]
olá @pterenzi , conseguiu algum retorno com o seu gerente, tive o mesmo problema aqui. Vou entrar em contato com eles pra entender certinho, Qualquer coisa nos avise.

grato

**Comment by pterenzi** [comment]
O problema estava, provavelmente, na configuração da carteira. Preenchi o campo com a carteira correta e não houve mais erros. Acabei de pagar um boleto teste e amanhã saberemos o resultado. Postarei aqui.

**Comment by felipe2santos** [comment]
@pterenzi conseguiu verificar?

Cláudio, sobre essa questão dos boletos com e registo, será que os bancos vão disponibilizar ou melhor isso? Pois isso vai ser um problema para os clientes que geram boletos com esses sistemas.

Enfim... estou começando a procurar uma solução para atender isso.

**Comment by claudiosmweb** [comment]
@felipe2santos tem que fazer usando a API de cada um deles, se eles tiverem.

**Comment by felipe2santos** [comment]
@claudiosmweb blz, tenho duas necessidades Banco do Brasil e Bradesco, vou ter que investir nisso. Ou vocês têm algum banco melhor para integrar?

**Comment by felipe2santos** [comment]
@claudiosmweb blz, tenho duas necessidades Banco do Brasil e Bradesco, vou ter que investir nisso. Ou vocês têm algum banco melhor para integrar?

**Comment by claudiosmweb** [comment]
Tenho nenhum projeto para desenvolver para nenhum desses dois bancos. Até mesmo nem acesso tenho para fazer algo assim.
