### ISSUE TITLE
Quando o Boleto é pago, a plataforma é avisada automaticamente? O boleto sai de "aguardando pagamento" para " Processando pagamento" ou seja pagamento 

### ISSUE THREAD

**Issue by niltonccf** [claudiosmweb/woocommerce-boleto#64]
Quando o Boleto é pago, a plataforma é avisada automaticamente? O boleto sai de "aguardando pagamento" para " Processando pagamento" ou seja pagamento ?

**Comment by claudiosmweb** [comment]
Não é avisado e aviso sobre isso na descrição do plugin.
