### ISSUE TITLE
Claudio, adiciona arquivos de retorno no plugin =)

### ISSUE THREAD

**Issue by niltonccf** [claudiosmweb/woocommerce-boleto#65]
Como contrato seu serviço para adiciona arquivos de retorno para mim? Nem que seja um pasta no plugin no qual seja enviado de 2 em 2 dias os arquivos de retorno que é disponibilizado pelo banco.

**Comment by claudiosmweb** [comment]
Não vou adicionar, além que este plugin vai deixar de ser legalmente valido no ano que vem, quando sera próibido usar boletos não registrados.
