### ISSUE TITLE
Informar que boleto foi pago

### ISSUE THREAD

**Issue by davidWebmaster** [claudiosmweb/woocommerce-boleto#66]
Olá galera,

Estou com o seguinte problema: Quando uma compra é feita usando boleto, preciso dar baixa manual, pelo que entendi no woocommerce o status usado para informar que o pedido foi pago é o **processando**.
Tenho feito isso mas mesmo assim o pedido continua aparecendo para mim na API como não pago. Isso é um bug ou não foi desenvolvido?

**Comment by claudiosmweb** [comment]
Aviso isso no plugin que não tem nada instalado/criado para retorno e que tem que ser manual mesmo.
