### ISSUE TITLE
DADOS DO PEDIDO CPF E CNPJ NAO APARECEM NO BANCO DE DADOS

### ISSUE THREAD

**Issue by guicma** [claudiosmweb/woocommerce-boleto#75]
Claudio, bom dia,

Queria saber se o Woocommerce tem alguma forma de exibir os dados "CPF e CNPJ" dos pedidos num banco de dados, ou extrair para um arquivo qualquer (XML, EXCELL, CSV, ou qualquer outro).

Pois no meu banco esses dados não aparecem.

Tentei usar um plugin chamado Advanced Order Export For WooCommerce, porem ele também não me mostra esse dados específicos,, mas mostra todos os outros campos.

Como fazer para extrair esses dados, que para nós é o campo mais importante.

Obrigado.

**Comment by claudiosanches** [comment]
Esse plugin é obsoleto e não deve ser usado por ninguém.
