### ISSUE TITLE
Trazer dados do pedido

### ISSUE THREAD

**Issue by guicma** [claudiosmweb/woocommerce-boleto#76]
Bom dia,

Em que tabela fica guardado as informações do cliente que fez o pedido?

Como nome, CPF, telefone, entre outros campos do checkout?

Pois eu olhei as tabelas, e não encontrei todos esses dados.

Obrigado.

**Comment by claudiosanches** [comment]
Esse plugin é obsoleto e não deve ser usado por ninguém.
